# Generated by Django 2.2.2 on 2019-06-10 15:07

from django.db import migrations
import json


def combine_names(apps, schema_editor):
    Mineral = apps.get_model('main_app', 'Mineral')
    input_file_path = 'assets/data/minerals.json'
    try:
        with open(input_file_path) as data:
            rocks = json.load(data)
    except Exception as e:
        print("Error in input file: {}\n{}".format(input_file_path, e))
    else:
        for rock in rocks:
            m = Mineral(**rock)
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
